### ISSUE TITLE
Having Problems when compiling

### ISSUE THREAD

**Issue by FangChuan98** [ComNetsHH/omnetpp-rpl#1]
Hi,
    I am new to OMNet and I am using your code to study RPL, and I follow your instructions to simulate the protocol but I encounter problems.
"
Description	Resource	Path	Location	Type
make: *** [Makefile:69: src_dir] Error 2	RPL		 	C/C++ Problem
Description	Resource	Path	Location	Type
make[1]: *** [Makefile:120: ../out/clang-release/src/ObjectiveFunction.o] Error 1	RPL		 	C/C++ Problem
"
  I have no idea in the _Properties_ : _OMNet++_: _Makemake_ , which one is the source folder and which one to build, could you give me some instructions. Much obliged.

**Comment by AREEG94FAHAD** [comment]
Same here

**Comment by AREEG94FAHAD** [comment]
> Hi,
> I am new to OMNet and I am using your code to study RPL, and I follow your instructions to simulate the protocol but I encounter problems.
> "
> Description Resource Path Location Type
> make: *** [Makefile:69: src_dir] Error 2 RPL C/C++ Problem
> Description Resource Path Location Type
> make[1]: *** [Makefile:120: ../out/clang-release/src/ObjectiveFunction.o] Error 1 RPL C/C++ Problem
> "
> I have no idea in the _Properties_ : _OMNet++_: _Makemake_ , which one is the source folder and which one to build, could you give me some instructions. Much obliged.

did you solve it ?

**Comment by yvshudrenko** [comment]
Should be solved with most recent update
