### ISSUE TITLE
The _MobileSink don't work 

### ISSUE THREAD

**Issue by loiloip** [ComNetsHH/omnetpp-rpl#3]
Hello everyone,
The _StaticTopology works well, but when I change the config to another configuration like : _MobileSink or _DynamicTopology or others it will show me this message error : 
check_and_cast(): Cannot cast (inet::LinearMobility*)RplNetwork.sink.mobility to type 'inet::StationaryMobility *' -- in module (inet::Rpl) RplNetwork.sink.rpl (id=48), during network initialization
![Capture d’écran_2021-09-26_10-17-06](https://user-images.githubusercontent.com/41823122/134801566-653f1964-0ee6-4609-a5fb-c4b15473d10c.png)

If you have any suggestion I would be very greatful for that, Thank you.

**Comment by yvshudrenko** [comment]
Hi, 
configs starting with an underscore are not supposed to be run, they're just used as a base for extension. `_MobileSink` seems to be an old unused config, so I removed it, please use configs with `-Dynamic` suffix as a base for mobility scenarios. The exception should also be solved at the latest version, please pull.
