### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by Rahi63** [ComNetsHH/omnetpp-rpl#5]
Hi, I am new to OMNet++. I ran this project step by step several times but I have a problem:

lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:114: ../out/clang-release/src/librpl.dll] Error 1
make[1]: Leaving directory '/d/OMNet++/resource/omnetpp-5.7-windows-x86_64/omnetpp-5.7/workspace1/rpl/src'
make: *** [Makefile:65: src_dir] Error 2
"make MODE=release all" terminated with exit code 2. Build might be incomplete.

Could you please guide me more?
It is worth mentioning that I imported "RPL and inet" into a new workspace and then applied changes according to the README.md
an also I imported project into sample folder but in both cases I had a problem.

**Comment by yvshudrenko** [comment]
Hi, sorry for late reply, can you please post full error log? The real error should be somewhere in the very beginning of it

**Comment by Rahi63** [comment]
Thank you for your response.
I already built the Openflow framework and connected it to the INET
framework.
However, when I try running a test scenario, the simulation crashes and I
get the error below.
[image: image.png]
After running in debug mode, I get the following information.
*<!> Error: Cannot load library '../../src//libopenflow6_dbg.so':
../../src//libopenflow6_dbg.so: undefined symbol:
_ZNK4inet16OperationalMixinIN7omnetpp13cSimpleModuleEE14refreshDisplayEv*
I have been stuck on these for a few days now and every troubleshooting
step I have tried proved unsuccessful.
Could you please help me?
Regards,

**Comment by yvshudrenko** [comment]
I'm not sure your question is related to this project, this is a simulation model of RPL routing protocol, it has nothing to do with OpenFlow. However, from the error log it also looks like a linkage issue, which were unfortunately pretty common for OMNeT++ installations on Windows: https://github.com/inet-framework/inet/issues/714, https://github.com/inet-framework/inet/issues/640, and seems to be fixed on latest 5.7, or 6.0 OMNeT.

**Comment by Rahi63** [comment]
Thank you so much for your reply. Am I allowed to email you if I encounter
another problem with Omnet?

Regards,
R. Samadi
